services:
  crafty:
    container_name: crafty
    image: registry.gitlab.com/crafty-controller/crafty-4:latest
    restart: always
    environment:
      - TZ=BR
    ports:
      - "8200:8000" # HTTP
      - "8243:8443" # HTTPS
      - "8123:8123" # DYNMAP
      - "19132:19132/udp" # BEDROCK
      - "25565:25565" # MC SERV PORT
      #- "25500-25600:25500-25600" # MC SERV PORT RANGE
    volumes:
      - /DATA/crafty/backups:/crafty/backups
      - /DATA/crafty/logs:/crafty/logs
      - /DATA/crafty/servers:/crafty/servers
      - /DATA/crafty/config:/crafty/app/config
      - /DATA/crafty/import:/crafty/import
    networks:
      - homelab

networks:
  homelab:
    external: true