# This file is part of the homelab project.

services:
  arm:
    container_name: arm
    image: automaticrippingmachine/automatic-ripping-machine:latest
    restart: unless-stopped
    privileged: true
    devices:
      - "/dev/sr0:/dev/sr0"
      - "/dev/sr1:/dev/sr1"
      - "/dev/sr2:/dev/sr2"
      - "/dev/sr3:/dev/sr3"
      - "/dev/nvidia0:/dev/nvidia0"
      - "/dev/nvidiactl:/dev/nvidiactl"
      - "/dev/nvidia-modeset:/dev/nvidia-modeset"
      - "/dev/nvidia-uvm:/dev/nvidia-uvm"
      - "/dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /srv/raid/arm/config:/etc/arm/config
      - /srv/raid/arm/music:/home/arm/music
      - /srv/raid/arm/logs:/home/arm/logs
      - /srv/raid/arm/media:/home/arm/media
    ports:
      - "8182:8080"
    environment:
      ARM_UID: "1000"
      ARM_GID: "1000"
      TZ: "America/Sao_Paulo"
      NVIDIA_DRIVER_CAPABILITIES: "all"
    networks:
      - homelab
    cpuset: "0,1,2,3" # Adjust according to your CPU cores
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
                - compute
                - video

networks:
  homelab:
    external: true
