services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '2080:80' # Public HTTP Port
      - '2443:443' # Public HTTPS Port
      - '2081:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    environment:
      # Uncomment this if you want to change the location of
      # the SQLite DB file within the container
      DB_SQLITE_FILE: "/data/database.sqlite"

      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    networks:
      - homelab
    volumes:
      - /DATA/nginx-proxy/data:/data
      - /DATA/nginx-proxy/letsencrypt:/etc/letsencrypt

networks:
  homelab:
    external: true