---
services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    hostname: syncthing
    environment:
      - PUID=0
      - PGID=100
      - TZ=Etc/UTC
    volumes:
      - /DATA/syncthing/config:/config
      - /DATA/syncthing/storage:/storage
      - /srv/dev-disk-by-uuid-c4527509-4f74-4020-9033-99a1385a279d/syncthing:/nas
      - /srv/dev-disk-by-uuid-c4527509-4f74-4020-9033-99a1385a279d/photos:/photos
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
    networks:
      - homelab

networks:
  homelab:
    external: true