services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      HOMEPAGE_ALLOWED_HOSTS: 192.168.1.88:3000 # required, may need port. See gethomepage.dev/installation/#homepage_allowed_hosts
    ports:
      - 3000:3000
    volumes:
      - /DATA/homepage/config:/app/config
      - /DATA/homepage/images:/app/images
      - /DATA/homepage/icons:/app/icons
    restart: unless-stopped
    networks:
      - homelab

networks:
  homelab:
    external: true