services:
  dashy:
    image: lissy93/dashy
    container_name: dashy
    volumes:
      - /DATA/dashy/my-config.yml:/app/user-data/conf.yml
    ports:
      - 8080:8080
    networks:
      - homelab
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  homelab:
    external: true