services:
  sftpgo:
    image: drakkan/sftpgo:v2.6.6
    container_name: sftpgo
    privileged: true
    ports:
      - 8880:8080
      - 2022:2022
      - 2121:2121
      - 10080:10080
    volumes:
      - /DATA/sftpgo/data:/srv/sftpgo
      - /DATA/sftpgo/home:/var/lib/sftpgo
    environment:
      - SFTPGO_HTTPD__BINDINGS__0__PORT=8080
      - SFTPGO_HTTPD__BINDINGS__0__ADDRESS=0.0.0.0
      - SFTPGO_WEBDAVD__BINDINGS__0__PORT=10080
      - SFTPGO_FTPD_BINDINGS_0_PORT=2121
      - SFTPGO_FTPD_BINDINGS_0_FORCE_PASSIVE_IP='127.0.0.1:8080'
      - SFTPGO_DATA_PROVIDER__DRIVER=mysql
      - SFTPGO_DATA_PROVIDER__HOST=mariadb
      - SFTPGO_DATA_PROVIDER__PORT=3306
      - SFTPGO_DATA_PROVIDER__DATABASE=sftpgo
      - SFTPGO_DATA_PROVIDER__USERNAME=sftpgo
      - SFTPGO_DATA_PROVIDER__PASSWORD=${MYSQL_PASSWORD}
      - SFTPGO_DEFAULT_ADMIN_USERNAME=admin
      - SFTPGO_DEFAULT_ADMIN_PASSWORD=admin
    networks:
      - homelab

networks:
  homelab:
    external: true
